apiVersion: v2
name: cat-api
description: A Helm chart for Cat API application with PostgreSQL database
type: application
version: 1.0.0
appVersion: "1.0"
maintainers:
  - name: DevOps Team
keywords:
  - cat-api
  - fastapi
  - postgresql
home: https://github.com/yourusername/cat-api
icon: https://example.com/icon.png
dependencies:
  - name: postgres
    version: 1.0.0
    repository: file://./charts/postgres
    alias: postgres
    condition: postgres.enabled
