{{- if .Values.catApi.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cat-api.fullname" . }}-migration
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.catApi.migration.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "cat-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      serviceAccountName: {{ include "cat-api.serviceAccountName" . }}
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: "{{ .Values.catApi.migration.image.repository }}:{{ .Values.catApi.migration.image.tag }}"
        imagePullPolicy: {{ .Values.catApi.migration.image.pullPolicy }}
        command: 
          - "uv"
          - "run"
          - "--group"
          - "migrations"
          - "alembic"
          - "upgrade"
          - "head"
        envFrom:
          - secretRef:
              name: postgres-secrets
          - configMapRef:
              name: {{ include "cat-api.fullname" . }}-config
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "cat-api.fullname" . }}-config
                key: DB_NAME
          - name: DATABASE_URL
            value: "postgresql+asyncpg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        {{- with .Values.catApi.migration.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
