{{- if .Values.catApi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cat-api.fullname" . }}-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.catApi.secrets.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.catApi.secrets.postgresql.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cat-api.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
